### PR TITLE
[incsrch] Cleanup windows stuff

### PR DESCRIPTION
**Pull request by rampitec**
Remove files not directly related to far2l build.
Add Belorussion lng to cmake, thanks for contribution.

### CODE REVIEW

**Comment by elfmz** [comment]
But why incsrch/gpl.txt also removed?

**Comment by rampitec** [comment]
> But why incsrch/gpl.txt also removed?

I just noticed this is the only plugin having it. Do you want me to restore it?

**Comment by elfmz** [comment]
yep its a kind of things to be better kept unless negotiated with original author(s)

**Comment by rampitec** [comment]
> yep its a kind of things to be better kept unless negotiated with original author(s)

Well, I am the original author ;) But I am OK anyway.

**Comment by elfmz** [comment]
ah:) then its (would be) ok

**Comment by rampitec** [comment]
> ah:) then its (would be) ok

Do you want me to add a separate change to remove it? I really do no want it to differ from general far2l licensing. The purpose it's there was to say: this stuff is free. I think far2l already has a copy for GPL license, although somewhere in the debian packaging, but it is still there. I am OK either way, just want to minimize source clutter.

**Pull request merged**
