### PR TITLE
python inside packaging

### PR DESCRIPTION
**Pull request by m32**

### CODE REVIEW

**Comment by elfmz** [comment]
2024-10-13T17:26:39.4658586Z /bin/sh: 1: /home/runner/work/far2l/far2l/python/src/build.sh: not found

**Comment by m32** [comment]
fixed

**Comment by spnethw** [comment]
Can't load `py:load ucharmap` on Arch.

```
[PYTHON 5063]: OpenPluginW@412 - OpenFrom=4 Item=-465454964
ERROR:far2l.pluginmanager:Uncaught exception
Traceback (most recent call last):
  File "/home/testuser/far2l_build/install/Plugins/python/plug/far2l/pluginmanager.py", line 44, in __inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/testuser/far2l_build/install/Plugins/python/plug/far2l/pluginmanager.py", line 103, in pluginInstall
    plugin = __import__(name)
             ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ucharmap'
GenerateConsoleCtrlEvent(2)
[PYTHON 6230]: MayExitFARW@528
WinState: saved flags=3 size={840, 448} pos={488, 547}
[PYTHON 6393]: ExitFARW@434
```

**Comment by m32** [comment]
@spnethw
ModuleNotFoundError means that there is no file with this name available via sys.path

I don't know if I did it right :( python files are loaded only from the user directory (~/.config/far2l/plugins/python) just like logger.ini and plugins.ini even if they exist in the plugin installation directory

**Comment by spnethw** [comment]
After copying ucharmap.py to ~/.config/far2l/plugins/python everything worked fine.

**Pull request merged**
