### PR TITLE
WIP: Hotkeys in mounst.sh, and Mac cleanup

### PR DESCRIPTION
**Pull request by singalen**
That. This had been bugging me for a long time now.
The shell code is horrible, and so is the ChDisk panel workaround. Criticism is welcome.

### CODE REVIEW

**Comment by sxored** [comment]
mounst != mounts

**Comment by elfmz** [comment]
Well, now hotkeys of Locations in Alt+F1/2 are manually editable - by F4 - just like plugins entries there. Is something missing there?

**Comment by singalen** [comment]
Amazing, thank you! This covers it.
I'll submit a better filter for Mac in a separate MR.

**Comment by singalen** [comment]
This is now obsolete, b/c of editable hotkeys and another commit.

**Pull request closed without merging**
