### PR TITLE
mounts sh space in path 

### PR DESCRIPTION
**Pull request by sxored**
enhancements for #1295 and fixes for #1375

### CODE REVIEW

**Comment by elfmz** [comment]
Firstly this script starts to look little bit chtonic :) i'd really like to rewrite it in C++ as only reason why its shell - cuz it was simplier to write in shell than in C++ (due to cross-compatibility mostly). Now it doesnt look simplier.
Secondly its looking not clean. I tried to measure its execution time (its another concern) and got bunch of stderr printouts:
image

**Comment by sxored** [comment]
Firstly, yes, I know :)

More parse logic needs more shell escaping... but "not everything can beat working code in debugging mode" :)

Secondly, this script can be rewritten as one big "sed" regular expression one-liner but what about  portability and readability... ;)

Thirdly, code is simple enough to work in portable way and this affects to its size but not readability... Wait, what ? :)
I eliminate one level of shell escaping compared to previous version.
Spaces and tabs in path are not issue anymore ?.. It needs testing "in wild"...

Warnings from "awk" are not hidden because "issues needs care and attention"...

"Too much" RE escaping that ignored by "awk" and "grep" is mainly for compatibility with various "shell" implementations. It also needs testing before compaction.

On other side I guess that current regular expressions in script is covering 70-90% of "df" and "mount" commands implementations. I will optimize their execution time later with compatibility in mind. Current RE-s are not optimized totally and have "too much" cycles and "too much" backtracking...

"awk" is chosen to minimize shell escaping, it is "old enough" and I guess it have advantages in portability and readability over "sed" that needs way more shell escaping in various environments.

Functions and other code organizing may come later...

Debugging code will be compacted after testing "in wild"...

**Comment by sxored** [comment]
Did you try this ?

"script for Linux to test mounts with loop devices ( sudo ) - "

https://github.com/elfmz/far2l/issues/1375#issuecomment-1289790293

And this debug mode of "mounts.sh" script

```sh
export FAR2L_DEBUG_MOUNTS_LOG=/tmp/somefile.log ; touch ${FAR2L_DEBUG_MOUNTS_LOG} ; time ~/.config/far2l/mounts.sh ;
```

and after that this commands with extracted "awk" scripts

```sh
time sh -x -c 'mount | grep -v -e " /proc" | awk -v debug=1 -f /tmp/script_1_mnt_prepare.awk | cat'
```

and this command in system other than Linux, FreeBSD, Darwin ( sysname="unknown" )

```sh
time sh -x -c 'df -T | grep -v -e " /proc" | time awk -v debug=1 -f /tmp/script_1_df_parse.awk | cat'
```

Log files can be found in "/tmp" directory...

Also script code logic can switch execution route with help of these inner variables

```sh
	# options values by default for compact output
	option_mnt_size_wide = 1;
	option_mnt_show_use_prc = 1;
	option_mnt_show_type = 1;
	option_mnt_show_fs = 1;

```

and

```sh
	# absolute path or ~/dir1 or ${env_var1}/dir2 or $(program args)/dir3 can be used in path field
	# anything that can be handled by shell in printf "example_path"
	# option_fav_nonabs_path should have value 1 to handle this
	# and value 0 to work with absolute path only
	option_fav_nonabs_path = 0;
```

**Comment by sxored** [comment]
Code is duplicated in "/tmp/script_1_mnt_prepare.awk" and "/tmp/script_1_df_parse.awk" because in former script there are variables that can be extracted from "mount_options" and can be shown to user in some way

**Comment by sxored** [comment]
Little more debugging...

```
time sh -x -c 'cat ~/.config/far2l/favorites | awk -v debug=1 --file /tmp/script_1_favorites.awk | cat'
```

"~/.config/far2l/favorites" example

```
-	home dirs
~/Desktop	~/Desktop
~/Documents	~/Documents
~/Downloads	~/Downloads
~/Music	~/Music
~/Pictures	~/Pictures
~/Public	~/Public
~/Videos	~/Videos
-	home work
~/download	~/download
~/projects	~/projects
~/various	~/various
-	home hidden
~/.config	~/.config
~/.local/share	~/.local/share
~/.cache	~/.cache
-	system
/tmp	/tmp
/var/tmp	/var/tmp

```

or without second field

```
-	home dirs
~/Desktop
~/Documents
~/Downloads
~/Music
~/Pictures
~/Public
~/Videos
-	home work
~/download
~/projects
~/various
-	home hidden
~/.config
~/.local/share
~/.cache
-	system
/tmp
/var/tmp

```

when this option in code is turned on

```sh
	option_fav_nonabs_path = 1;

```

script output will be like this

```
-	home dirs
/home/user/Desktop	          	~/Desktop
/home/user/Documents	          	~/Documents
/home/user/Downloads	          	~/Downloads
/home/user/Music	          	~/Music
/home/user/Pictures	          	~/Pictures
/home/user/Public	          	~/Public
/home/user/Videos	          	~/Videos
-	home work
/home/user/download	          	~/download
/home/user/projects	          	~/projects
/home/user/various	          	~/various
-	home hidden
/home/user/.config	          	~/.config
/home/user/.local/share	          	~/.local/share
/home/user/.cache	          	~/.cache
-	system
/tmp	          	/tmp
/var/tmp	          	/var/tmp

```

**Comment by sxored** [comment]
I forgot to thank authors and contributors of this project for idea to parse "df" and "mount" output with regular expressions

"generic colouriser"

https://github.com/garabik/grc

**Comment by elfmz** [comment]
/me rewrote mountpoints enumerationg in C++, with 1 second timeout to avoid stucks

**Pull request closed without merging**
