### PR TITLE
update mounts.sh to include fs use % and info for favorites

### PR DESCRIPTION
**Pull request by sxored**
```
$ time ~/.config/far2l/mounts.sh

/	3.0G 9.6G 68%	    ext4
/usr/lib/modules	3.0G 9.6G 68%	 overlay
/run	785M 786M  1%	   tmpfs
/mnt/backup	680M 176G 100%	    ext4
/mnt/custom	_17G 147G 88%	    ext4
-	home dirs
/home/user/Desktop	= 4.0K	~/Desktop
/home/user/Documents	= 1.1G	~/Documents
/home/user/Downloads	= 1.1G	~/Downloads
/home/user/Music	=  38M	~/Music
/home/user/Pictures	=  19M	~/Pictures
/home/user/Public	= 4.0K	~/Public
/home/user/Videos	= 4.0K	~/Videos
-	home hidden
/home/user/.config	= 351M	~/.config
/home/user/.local/share	=  34M	~/.local/share
/home/user/.cache	=  96M	~/.cache
-	mnt
/mnt/backup	/dev/sda1	/mnt/backup
/mnt/custom	/dev/sda2	/mnt/custom
/mnt/floppy	= 4.0K	/mnt/floppy
/mnt/remote1	= 4.0K	/mnt/remote1
/mnt/remote2	= 4.0K	/mnt/remote2

real	0m0.149s
user	0m0.087s
sys	0m0.107s
```

### CODE REVIEW

**Comment by sxored** [comment]
make it optional in favorites

**Comment by sxored** [comment]
```
-	home dirs
/home/user/Desktop	~/Desktop	du
/home/user/Documents	~/Documents	du
/home/user/Downloads	~/Downloads	du
/home/user/Music	~/Music		du
/home/user/Pictures	~/Pictures	du
/home/user/Public	~/Public	du
/home/user/Videos	~/Videos	du
-	home work
/home/user/download	~/download	du
/home/user/projects	~/projects	du
-	home hidden
/home/user/.config	~/.config	du
/home/user/.local/share	~/.local/share	du
/home/user/.cache	~/.cache	du
-	mnt
/mnt/backup	/mnt/backup	mnt
/mnt/custom	/mnt/custom	mnt
/mnt/floppy	/mnt/floppy	mnt
/mnt/remote1	/mnt/remote1	mnt
/mnt/remote2	/mnt/remote2	mnt
```

**Comment by sxored** [comment]
new proposed format of favorites file is compatible with old format

```
##########################################################
# This optional file may contain per-user extra values added to df output,
# optional 3rd parameter can have predefined values 'du' / 'mnt'
# its content must be looking like:
#path1<TAB>info1<TAB>du
#path2<TAB>info2<TAB>mnt
#-<TAB>separator_label
#path3<TAB>info3
FAVORITES=~/.config/far2l/favorites

```

example

```
-	home dirs
~/Desktop		~/Desktop
~/Documents	:du	~/Documents
~/Downloads	:du	~/Downloads
~/Music	:du	~/Music
~/Pictures	:du	~/Pictures
~/Public	:du	~/Public
~/Videos	:du	~/Videos
-	home work
~/download	:du	~/download
~/projects	:du	~/projects
~/various	:du	~/various
-	home hidden
~/.config	:du	~/.config
~/.local/share	:du	~/.local/share
~/.cache	:du	~/.cache
-	system
/tmp	:du	/tmp
/var/tmp	:du	/var/tmp
-	mnt
/	:mnt	/ = root dir
/home	:mnt	/home
/mnt/backup	:mnt	/mnt/backup
/mnt/custom	:mnt	/mnt/custom
/mnt/floppy	:mnt	/mnt/floppy
/mnt/media	:mnt	/mnt/media
/mnt/cdrom	@cdrom	/mnt/cdrom
/mnt/remote1	:mnt	/mnt/remote1
/mnt/remote2	:mnt	/mnt/remote2

```

**Comment by sxored** [comment]
corrected format description in previous comment

**Comment by elfmz** [comment]
Total numbers allows estimation usage for eye and adding such information will clutter output that sometime has somewhat limited even space for printing...

**Pull request closed without merging**
