### PR TITLE
Simplify macOS install process

### PR DESCRIPTION
**Pull request by yurikoles**

### CODE REVIEW

**Comment by elfmz** [comment]
IMHO its better to leave both ways. Say, easy and make all by you own hands.

**Comment by yurikoles** [comment]
@elfmz good point! I had updated my commit, you can check-out result [here](https://github.com/yurikoles/far2l/blob/brew/README.md).

**Comment by elfmz** [comment]
also since you changed build dir from outer location then add to .gitignore:
`build/`
..to avoid git status garbaging

**Comment by yurikoles** [comment]
done

**Pull request merged**
