### PR TITLE
fix #1634

### LINKED ISSUE #1634: spaces are inserted instead of tabs sometimes
1. open new file in editor
2. switch to T4 mode (do not expand tabs, tab size = 4)
3. press `Right Arrow` 4 times
4. press `i`
5. press `F5`
6. You will see 4 spaces inserted at the beginning of a line. But it should be 1 tab instead.

### PR DESCRIPTION
**Pull request by unxed**
fix #1634

insert tabs if possible instead of spaces if cursor is beyond EOL and char key is pressed (or paste happend) if tab mode is 0

### CODE REVIEW

**Comment by elfmz** [comment]
Not sure if its valid/expected behavior, why tabs should be inserted just due to cursor movement?

**Comment by unxed** [comment]
Oh, it's not about inserting tabs on cursor movement. It's about situation when you start typing (or pasting) having cursor beyond end of a line. Old code used previous lines to detect if tabs or spaces should be used to fill the gap between end of line and cursor position. But previous line may have no tabs or spaces at all. More of this, previous line is not available if you are at the first line of a file. So new code uses tabs mode to detect if tabs or spaces should be used for filling the gap from end of line to cursor position. Also it fixes a weird bug when tab or space sometimes was inserted after cursor position and not before it as it should.

**Comment by elfmz** [comment]
I'd say that this behavior makes sense and its same in FAR3. Note that setting is about what to do on pressing Tab key, but not about expanding anything by tabs.
I see however one inconsistency in the original behavior that if it uses same amount of tabs as previous line, causing mixed tab/space indentation to next line, like:
```
	some
		original
	lines
	            newly typed line
```
I'd suggest to keep original behavior if indentation way of other line(s) is known, and use TABs/Spaces setting only if its unknown. And use tabs to fill all space from position zero to beginning of line. HOWEVER if line being typed goes after another text, like
```
	some
		original
	lines
	existing          newly typed
```
then don't use tabs between 'existing' and 'newly typed'

**Comment by unxed** [comment]
added two additional conditions:

- if space is found at the beginning of one of previous lines, do not use tabs for filling gaps from line end to cursor position
- if non-space char is found in the current line, do not use tabs for filling such gaps also

**Comment by unxed** [comment]
забыл важное! вставка пробелов/табов в Undo не учитывается (и так до меня ещё было, кстати — противный баг).

надо поправить. #1650

**Pull request merged**
