### PR TITLE
MacPorts compilation

### PR DESCRIPTION
**Pull request by singalen**
@lieff, sorry, I undid some of your CMake changes, and added a more general approach (using pkg-config).
Can you please try if this compilation works for you?

### CODE REVIEW

**Comment by singalen** [comment]
Hmm, `target_link_options` only appeared in CMake 3.13. Will add a workaround compatible with older versions.

**Comment by lieff** [comment]
Sorry for the delay.
Hmm, with latest cmake
```
bash-3.2$ cmake -DCMAKE_INSTALL_PREFIX=/usr -DUSEWX=yes -DCMAKE_BUILD_TYPE=Release ..
-- libssh found
CMake Error at /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/FindThreads.cmake:191 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  WinPort/CMakeLists.txt:86 (find_package)

**Comment by singalen** [comment]
Completely removed the Mac compilation hacks, and yet it built!

Well, somebody else might still have to add this spell to `cmake` invocation:
```
cmake .. \
-DwxWidgets_CONFIG_EXECUTABLE=/opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/bin/wx-config \
-DwxWidgets_wxrc_EXECUTABLE=/opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/bin/wxrc
```
@lieff, what's your opinion now?

**Comment by lieff** [comment]
Cool :) Looks much cleaner now. /opt/local/Library/Frameworks/wxWidgets.framework - it's locally built version?
I'm using 
```
brew tap cdalvaro/tap
brew install cdalvaro/tap/wxmac
cmake .. -DwxWidgets_CONFIG_EXECUTABLE=/usr/local/Cellar/wxmac/3.1.3/bin/wx-config -DwxWidgets_wxrc_EXECUTABLE=/usr/local/Cellar/wxmac/3.1.3/bin/wxrc-3.1
```
and I can confirm it works.

**Pull request merged**
