### PR TITLE
Update macOS section of README

### LINKED ISSUE #1078: MacOS brew error: invalid option: --without-wxmac
Readme states that I can install with the following command:

```
brew install --HEAD yurikoles/yurikoles/far2l --without-wxmac
```

Actual output:

```
$ brew install --HEAD yurikoles/yurikoles/far2l --without-wxmac
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
lastz                                                                                          openssl@3
==> Updated Formulae
Updated 93 formulae.
==> New Casks
cloudash                                       dropbox-capture                                firmaec                                        tidelift
==> Updated Casks
Updated 84 casks.
==> Deleted Casks
microsoft-lync                                                                                 microsoft-r-open

Usage: brew install [options] formula|cask [...]

Install a formula or cask. Additional options specific to a formula may be
appended to the command.

Unless HOMEBREW_NO_INSTALL_CLEANUP is set, brew cleanup will then be run for
the installed formulae or, every 30 days, for all formulae.

  -d, --debug                      If brewing fails, open an interactive
                                   debugging session with access to IRB or a
                                   shell inside the temporary build directory.
  -f, --force                      Install formulae without checking for
                                   previously installed keg-only or
                                   non-migrated versions. When installing
                                   casks, overwrite existing files (binaries
                                   and symlinks are excluded, unless
                                   originally from the same cask).
  -v, --verbose                    Print the verification and postinstall
                                   steps.
      --formula, --formulae        Treat all named arguments as formulae.
      --env                        Disabled other than for internal Homebrew
                                   use.
      --ignore-dependencies        An unsupported Homebrew development flag to
                                   skip installing any dependencies of any
                                   kind. If the dependencies are not already
                                   present, the formula will have issues. If
                                   you're not developing Homebrew, consider
                                   adjusting your PATH rather than using this
                                   flag.
      --only-dependencies          Install the dependencies with specified
                                   options but do not install the formula
                                   itself.
      --cc                         Attempt to compile using the specified
                                   compiler, which should be the name of the
                                   compiler's executable, e.g. gcc-7 for GCC
                                   7. In order to use LLVM's clang, specify
                                   llvm_clang. To use the Apple-provided
                                   clang, specify clang. This option will
                                   only accept compilers that are provided by
                                   Homebrew or bundled with macOS. Please do
                                   not file issues if you encounter errors
                                   while using this option.
  -s, --build-from-source          Compile formula from source even if a
                                   bottle is provided. Dependencies will still
                                   be installed from bottles if they are
                                   available.
      --force-bottle               Install from a bottle if it exists for the
                                   current or newest version of macOS, even if
                                   it would not normally be used for
                                   installation.
      --include-test               Install testing dependencies required to
                                   run brew test formula.
      --HEAD                       If formula defines it, install the HEAD
                                   version, aka. main, trunk, unstable,
                                   master.
      --fetch-HEAD                 Fetch the upstream repository to detect if
                                   the HEAD installation of the formula is
                                   outdated. Otherwise, the repository's HEAD
                                   will only be checked for updates when a new
                                   stable or development version has been
                                   released.
      --keep-tmp                   Retain the temporary files created during
                                   installation.
      --build-bottle               Prepare the formula for eventual bottling
                                   during installation, skipping any
                                   post-install steps.
      --bottle-arch                Optimise bottles for the specified
                                   architecture rather than the oldest
                                   architecture supported by the version of
                                   macOS the bottles are built on.
      --display-times              Print install times for each package at the
                                   end of the run.
  -i, --interactive                Download and patch formula, then open a
                                   shell. This allows the user to run
                                   ./configure --help and otherwise
                                   determine how to turn the software package
                                   into a Homebrew package.
  -g, --git                        Create a Git repository, useful for
                                   creating patches to the software.
      --cask, --casks              Treat all named arguments as casks.
      --[no-]binaries              Disable/enable linking of helper
                                   executables (default: enabled).
      --require-sha                Require all casks to have a checksum.
      --[no-]quarantine            Disable/enable quarantining of downloads
                                   (default: enabled).
      --skip-cask-deps             Skip installing cask dependencies.
      --appdir                     Target location for Applications (default:
                                   /Applications).
      --colorpickerdir             Target location for Color Pickers (default:
                                   ~/Library/ColorPickers).
      --prefpanedir                Target location for Preference Panes
                                   (default: ~/Library/PreferencePanes).
      --qlplugindir                Target location for QuickLook Plugins
                                   (default: ~/Library/QuickLook).
      --mdimporterdir              Target location for Spotlight Plugins
                                   (default: ~/Library/Spotlight).
      --dictionarydir              Target location for Dictionaries (default:
                                   ~/Library/Dictionaries).
      --fontdir                    Target location for Fonts (default:
                                   ~/Library/Fonts).
      --servicedir                 Target location for Services (default:
                                   ~/Library/Services).
      --input-methoddir            Target location for Input Methods (default:
                                   ~/Library/Input Methods).
      --internet-plugindir         Target location for Internet Plugins
                                   (default: ~/Library/Internet Plug-Ins).
      --audio-unit-plugindir       Target location for Audio Unit Plugins
                                   (default:
                                   ~/Library/Audio/Plug-Ins/Components).
      --vst-plugindir              Target location for VST Plugins (default:
                                   ~/Library/Audio/Plug-Ins/VST).
      --vst3-plugindir             Target location for VST3 Plugins (default:
                                   ~/Library/Audio/Plug-Ins/VST3).
      --screen-saverdir            Target location for Screen Savers (default:
                                   ~/Library/Screen Savers).
      --language                   Comma-separated list of language codes to
                                   prefer for cask installation. The first
                                   matching language is used, otherwise it
                                   reverts to the cask's default language. The
                                   default value is the language of your
                                   system.
  -q, --quiet                      Make some output more quiet.
  -h, --help                       Show this message.
Error: invalid option: --without-wxmac
```

See the error above, the command seems just doesn't work.

Version:

```
$ brew --version
Homebrew 3.2.13
Homebrew/homebrew-core (git revision 3fb1092757; last commit 2021-09-24)
Homebrew/homebrew-cask (git revision 58bde8e7f0; last commit 2021-09-24)
```

### PR DESCRIPTION
**Pull request by yurikoles**
Closes #1078
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

### CODE REVIEW

**Comment by elfmz** [comment]
Please keep <https://github.com/elfmz/far2l/releases> as first choice, at least its a versions considered more stable than usual

**Comment by yurikoles** [comment]
It's actually the [very same artifacts](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/far2l.rb) that is being installed by cask.

**Comment by yurikoles** [comment]
Don't be confused by far2l _formula_ from my tap, _cask_ is accepted upstream.

**Comment by elfmz** [comment]
ok, but if somebody will again report crashes inside wx - i will move it back:)

**Pull request merged**
