### PR TITLE
Simplify build instructions

### PR DESCRIPTION
**Pull request by yurikoles**
Notes: 
* `cmake --build` calls `make` with all available cores by default. 
* Same for `-G Ninja` or direct call to `ninja`. Actually `ninja`'s `-j` parameter is intended to _limit_ parallel jobs.

Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

### CODE REVIEW

**Comment by elfmz** [comment]
Something completely wrong with that -B argument, see (cmake version 3.10.2):
```
/home/user/projects/far2l$ cmake -DUSEWX=yes -DCMAKE_BUILD_TYPE=Release -S . -B build
CMake Error: The source directory "/home/user/projects/far2l/build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

/home/user/projects/far2l$ mkdir build && cmake -DUSEWX=yes -DCMAKE_BUILD_TYPE=Release -S . -B build
CMake Error: The source directory "/home/user/projects/far2l/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

So please revert command lines as was, although formatting changes are ok

**Comment by yurikoles** [comment]
You are right, it seems that it was added in `cmake` 3.14, going to revert this changes.

**Comment by yurikoles** [comment]
I reverted this change and rebased in order to keep history cleaner.

**Comment by elfmz** [comment]
please just keep it as was:) cuz
- cmake --install also not recognized
- cmake --build doesnt parallelize build and options like CMAKE_BUILD_PARALLEL_LEVEL and -j also added in cmake somewhat later than currently present in Ubuntu 18. Non-paralleled far2l build takes too long.

**Pull request closed without merging**
