### PR TITLE
fixed mounts sh freezing for network mounts

### PR DESCRIPTION
**Pull request by sxored**
fix for #1295

### CODE REVIEW

**Comment by elfmz** [comment]
Sorry but i'd like simple possible solution, please check recent commit if it resolves original issue

**Comment by sxored** [comment]
also this simpler approach does not work as expected when there are more than one network mounts to different hosts

it does not show any network mount in list when only one of them is not reachable

while mount command work flawlessly in almost all cases and OS-es

that's why i extended code with checks and gathering info from df command for every mounted device one by one ...

**Comment by sxored** [comment]
please see this

https://stackoverflow.com/questions/601543/command-line-command-to-auto-kill-a-command-after-a-certain-amount-of-time

**Comment by sxored** [comment]
previous link is from this answer

https://stackoverflow.com/questions/37981492/how-to-timeout-a-group-of-commands-in-bash/61888916#61888916

**Comment by elfmz** [comment]
Yes, df -l abscent on busybox, but it works on MacOS, while your script fallbacks to old behavior there.
And still need to think how to simplify it. This shell script appeared cuz it was too complicated to write in C++ due to there is no universal way to get mount points across all OSes, but now its also looks complicated..So may be consider switch to C++ ) 
Few obvious things:
1 FT_HEADER not needed (at least it was not needed for code that parses output of df)
2 indent awk scripts
...and remove those underscores in disk space numbers.

**Comment by sxored** [comment]
one can use uniq and sort commands to remove "duplicates" ( they are not really duplicates, only by device name ) in mount command output to imitate df output ...

but there are different implementations of this commands in various environments ( gnu/nongnu/bsd/etc )

fortunately awk, grep and sed have more or less similar implementation almost everywhere )

and we can use them with help of "uniq -w NN" for this task

```
$ mount | grep -v -e " /proc\(/[\/a-z_]\+\)* " -e " /sys\(/[a-z_,]\+\)* " -e " /dev/\(pts\|hugepages\|mqueue\) " -e " /run/user/\([0-1]\+\)/doc " | awk '{ print $1 " $ " $1 " " $5 " " $3 " " $NF }' | grep -n -e "" | sed -e "s_^\([1-9]:\)_0\1_" | sed -e "s_^\([0-9][0-9]:\)_0\1_" | sed -e "s_^\([0-9]\+\):\(\/dev\/[^\ ]\+\)_000:~\2_" | column -t

000:~/dev/vda1           $  /dev/vda1            ext4      /                 (rw,noatime,discard)
002:none                 $  none                  overlay   /usr/lib/modules  (rw,relatime,lowerdir=/tmp/modules,upperdir=/sysroot/lib/modules,workdir=/sysroot/lib/.modules_work)
003:devtmpfs             $  devtmpfs              devtmpfs  /dev              (rw,nosuid,noexec,size=2000228k,nr_inodes=500057,mode=755,inode64)
004:tmpfs                $  tmpfs                 tmpfs     /dev/shm          (rw,size=1048576k,inode64)
005:tmpfs                $  tmpfs                 tmpfs     /run              (rw,nosuid,nodev,size=804928k,nr_inodes=819200,mode=755,inode64)
006:tmpfs                $  tmpfs                 tmpfs     /run/lock         (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
000:~/dev/vdb1           $  /dev/vdb1             ext4      /home             (rw,relatime,discard)
000:~/dev/vdb1           $  /dev/vdb1             ext4      /usr/local        (rw,relatime,discard)
000:~/dev/vdb1           $  /dev/vdb1             ext4      /var/spool/cron   (rw,relatime,discard)
011:tmpfs                $  tmpfs                 tmpfs     /run/user/1000    (rw,nosuid,nodev,relatime,size=402460k,nr_inodes=100615,mode=700,uid=1000,gid=1000,inode64)
000:~/dev/vdi            $  /dev/vdc1             fuseblk   /mnt/media        (rw,nosuid,nodev,noexec,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,user)
000:~/dev/vdk            $  /dev/vdd1             ext4      /mnt/backup       (ro,nosuid,nodev,noexec,relatime,norecovery,user)
000:~/dev/vdj            $  /dev/vde1             ext4      /mnt/custom       (rw,nosuid,nodev,noexec,relatime,user)
015://a.b.c.d/share      $  //a.b.c.d/share       cifs      /mnt/remote1      (rw,nosuid,nodev,noexec,relatime,vers=2.1,cache=strict,...)
016://a.b.c.d/share      $  //a.b.c.d/share       cifs      /mnt/remote2      (rw,nosuid,nodev,noexec,relatime,vers=2.1,cache=strict,...)
```

"column -t" is for human eyes only and is not necessary

i do not forgot about "duplicated" network mounts

in far2l one can unmount multiple network mounts separately

```
$ mount | grep -v -e " /proc\(/[\/a-z_]\+\)* " -e " /sys\(/[a-z_,]\+\)* " -e " /dev/\(pts\|hugepages\|mqueue\) " -e " /run/user/\([0-1]\+\)/doc " | awk '{ print $1 " $ " $1 " " $5 " " $3 " " $NF }' | grep -n -e "" | sed -e "s_^\([1-9]:\)_0\1_" | sed -e "s_^\([0-9][0-9]:\)_0\1_" | sed -e "s_^\([0-9]\+\):\(\/dev\/[^\ ]\+\)_000:~\2_" | uniq -w 16 | awk '{ print $3 " " $4 " [size] [used] [avail] [use] " $5 " " $NF }' | column -t

/dev/vda1            ext4      /                 (rw,noatime,discard)
none                  overlay   /usr/lib/modules  (rw,relatime,lowerdir=/tmp/modules,upperdir=/sysroot/lib/modules,workdir=/sysroot/lib/.modules_work)
devtmpfs              devtmpfs  /dev              (rw,nosuid,noexec,size=2000228k,nr_inodes=500057,mode=755,inode64)
tmpfs                 tmpfs     /dev/shm          (rw,size=1048576k,inode64)
tmpfs                 tmpfs     /run              (rw,nosuid,nodev,size=804928k,nr_inodes=819200,mode=755,inode64)
tmpfs                 tmpfs     /run/lock         (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
/dev/vdb1             ext4      /home             (rw,relatime,discard)
tmpfs                 tmpfs     /run/user/1000    (rw,nosuid,nodev,relatime,size=402460k,nr_inodes=100615,mode=700,uid=1000,gid=1000,inode64)
/dev/vdc1             fuseblk   /mnt/media        (rw,nosuid,nodev,noexec,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,user)
/dev/vdd1             ext4      /mnt/backup       (ro,nosuid,nodev,noexec,relatime,norecovery,user)
/dev/vde1             ext4      /mnt/custom       (rw,nosuid,nodev,noexec,relatime,user)
//a.b.c.d/share       cifs      /mnt/remote1      (rw,nosuid,nodev,noexec,relatime,vers=2.1,cache=strict,...)
//a.b.c.d/share       cifs      /mnt/remote2      (rw,nosuid,nodev,noexec,relatime,vers=2.1,cache=strict,...)
```

**Comment by sxored** [comment]
> ... due to there is no universal way to get mount points across all OSes, but now its also looks complicated..So may be consider switch to C++ )

why not ?

mount and df command implementations are almost all opensource these days )

> Few obvious things:
> 1 FT_HEADER not needed (at least it was not needed for code that parses output of df)

for human eyes only

> 2 indent awk scripts

i will reformat code

> ...and remove those underscores in disk space numbers.

it is necessary to indent the first number by some "non-space" symbol, because far2l removes all the first "space" symbols ...

**Comment by sxored** [comment]
> ... And still need to think how to simplify it. This shell script appeared cuz it was too complicated to write in C++ ...

Everything should be made as simple as possible, but not simpler. ( Albert Einstein? Louis Zukofsky? Roger Sessions? William of Ockham? Anonymous? )

(https://quoteinvestigator.com/2011/05/13/einstein-simple/#comment-4418)

> Eric says:
> [November 19, 2012 at 10:32 pm]

> The Einstein quote does NOT mean “make it simple enough to understand,” as Dodd suggested above. Einstein spoke and wrote more than once about simplification. More to the point, he was decidedly AGAINST simplifying to the point that laypersons might understand ...

**Comment by sxored** [comment]
> Yes, df -l abscent on busybox, but it works on MacOS, while your script fallbacks to old behavior there.

This is because I have not yet had the opportunity to test the implementation of these programs ( mount, df, sed, grep, sort, uniq, awk, timeout ) on macOS

**Comment by sxored** [comment]
interensting reading

https://gobolinux.org/doc/articles/clueless.html

> Fortunately, like with the live CD, we have nowadays a technological advancement that serves as a real solution to the problem: union mounts, also known as overlay filesystems. The idea is that you can mount several partitions in the same directory. This way, the semantics of /Programs as “the collection of all programs available in the system” is retained, independently of the physical location of the actual data. File systems are all about abstraction (we don't refer to files based on their track, sector and cylinder address), this progresses a step further. Overlay filesystems are very flexible: the sysadmin, for example, can overlay site-specific settings for an application on top of the defaults exported over NFS. Unfortunately, it is not in widespread use, for reasons beyond my understanding. The Plan 9 operating system has it as one of its basic filesystem operations: the bind command (in Plan 9, for example, you don't need a $PATH variable, because all directories containing executables are “bound” in a single directory). There is an implementation of an overlay filesystem for Linux: ovlfs.

**Comment by sxored** [comment]
df -l may take a long time to process the request also in case of faulty local storage

I know it's rare, but not for system administrators using far2l to save some files

**Pull request merged**
