### PR TITLE
debugging and dynamic python plugins

### PR DESCRIPTION
**Pull request by m32**

### CODE REVIEW

**Comment by elfmz** [comment]
i dont think its right idea to commit vscode project, especially as a part of files that gonna be copied to user's system during make install

**Comment by m32** [comment]
Unfortunately, I agree, but I had no idea where to copy these files to be also available without installing far2l sources.
Do you have any suggestion?

BTW How to install files in ~ .config/far2l/plugins/python?

**Comment by elfmz** [comment]
just dont commit them

**Comment by elfmz** [comment]
or put them inside of plugins sources dir with instructions how to use them (or with shell script that will copy them where necessary)

**Pull request closed without merging**
